### ISSUE TITLE
jamm on fast inserters

### ISSUE THREAD

**Issue by deltaone** [theRustyKnife/CraftingCombinator#24]
factorio 0.15.10
crafting_combinator_0.7.2

on refresh rate 60 - jamm after 1-2 iterations, 10-25 - ok

and please provide some working blueprints as examples on forum (examples of organizing small and simple production with your mod, in/out production and materials, methods of transporter connections, control logic, and etc), thx!

test setup:
upper input belt is mixed copper & iron plates

0eNrtWV2OmzAQvoufocI2f4nUlfrSp/YEVYUIOLuWwEbGbButcoDeoyfrSWpDNskSDHa2q/RhX3YFCZ9n5vvmm0F5ApuqI42gTIL1E6AFZy1Yf3sCLb1neaXvyV1DwBpQSWrgAZbX+ipvW1JvKsru/TovHigjPgJ7D1BWkp9gDffeIoQUOWsbLqS/IZU8exjtv3uAMEklJUMw/cUuY129IUKhmzA80PBWPcaZPlVB+YkHdupfuNcBjWCQM0ykgiypIMXwGZoAxUfQbd5Kn7KWCKk+uMSMZkIL7UOLrUOL7EEja9DYOl/8nO8LzHgCMzliFiLfSiWyrOD1hrJccpF9/volO4rWL3OZ+43gkmuRZQPSxOnh6XSlcSl4lW3IQ/5IudBf2dJKRW0lfeeYiiLTCFlJ2l7mBe90t+Gj4EOLbrnm1JqXXUXM50b771PiS2cPfb7nn+7Nl/uM7LAvPhsuW/1dqP/cC0LYeaPTUjV5oqObCG9lL+PQWsYwsEfF9qgnp2olIZVfPGguLiHRjBdAZN1icLLqk5Fh+3yRfb4OvgXtUSPbAsC5Msb/3lWCd1OxNRWYvN5VglebSnoWmb5GqcFkYGqtZAch21tXYA2KHJwrHVCRBar7joUmdyz3JQtP4uD51dO4wuhcVaa0V3/Bm4YIv8g3FQFTp4Su2wxa3mbQyb5+cF4StjQF0H5a0YKUYz3jwKBfFLsODZtMEkcS4DUcnDqvrfOq8kmlYhK08Buunrg4I5wvmmm3eOkDWGVWUFF0VA6+YCrrylUg0OKVIXAUCLQXCIrGmZpSw9BVMTapITcyDxlCpw4YJbgyJXiykFKJsdQinBk2+EN0jOU8y+lRf0BUI42V9Bj0lopWZktD+GVDaPhW5nqoRoG+qptc9CGuwZ9fv9VzvJNNNwH7SIXs1J1Tyftv+J8G1GaX9cM62wpeZ5QpDLDe5lVL9g7lDl82CpyqvgeQsfVwNAYwsBVexRa6HVswGNN1d2uy8AJZ6SUXs9zFltxFTtxFb9dpC1V+pm5M3MdbExdfjCPPQAm+HFwHCi1wjQTGVxGI3gk0uNwMgaETgZfuacJNLKlOnKhObk41dKB6ybrdubbyRbTgoyhdMGLjjpZeNRTxf7TC3FnTNayKnKll8VCbN91jFkaf5QsCXl218EYOkaOxePBUpytf6Mu5PvuBxwOPRLTD610YogjGYRqo1+2/bI3epw==

**Comment by theRustyKnife** [comment]
Hi, the jamming situation seems to be quite complicated, so it may take a while for me to come up with a way to fix it. It seems to be related to the inserters' stack size - if it's set to 1, everything works correctly.
I'm not quite sure why it only happens with certain refresh rates. My best guess for the moment is that the recipe switch happens to occur in the middle of the inserter's attempt to grab multiple items from the belt.

As for the blueprints - I'll make sure there are some 'starter' ones available. I' also planning to make some kind of pictured documentation or something, so that would go along with that nicely.

Cheers TRK

**Comment by deltaone** [comment]
thx, for info ...

**Comment by theRustyKnife** [comment]
To give a bit of an update on this situation:  
So far, I haven't found a way to fix this. It seems that there is just no way to force the inserters to abandon their current 'grabbing session' and move on to another item. I think it might be sensible to make an API request for something that would allow this, but I would have to figure out what that would be first.

Cheers TRK

**Comment by lightoze** [comment]
Is it possible to schedule `empty_inserters` execution a few (26 for fast inserter) ticks after `update()` is called?

**Comment by Marek-Arnold** [comment]
should be fixed with PR #40

**Comment by theRustyKnife** [comment]
As said above, this should now work.
