### ISSUE TITLE
Recipes with multiple output items dont multiply correctly

### ISSUE THREAD

**Issue by CodingBenny** [theRustyKnife/CraftingCombinator#44]
This has bugged me for a while:

If you want to find the ingridients for copper wire for example with mulityplication enabled, the recipe combinator suggests that you need one copper plate per copper wire.

In reality you get 2 copper wires per copper plate.

**Comment by theRustyKnife** [comment]
The way I intended it is that the input signals represent the recipe, rather than the outputs. So it's more like one copper wire represents one craft of the recipe, which takes one plate. I realize it takes some extra processing to do what you are trying to do with this method, but it's the most consistent I could come up with.

What you're suggesting would mean the combinator behaves differently for different recipes. For example the cracking recipes aren't signaled by their outputs so they would always just get multiplied by the raw signal value, while say copper wires will get multiplied using the new system. This could be mitigated to some extent by deciding what the "main" product is, but that still doesn't address potential recipes with no products.

And that's not even mentioning that the current system is already quite confusing and this would just make it even worse imo.

I'll think about maybe adding this as an option so I'll leave #45 open for now, but I'm closing this, since it's not really an issue.

**Comment by CodingBenny** [comment]
> This could be mitigated to some extent by deciding what the "main" product is, but that still doesn't address potential recipes with no products.

The "main" product is the one that is requested by the signal. The item we are trying to craft.

> And that's not even mentioning that the current system is already quite confusing and this would just make it even worse imo.

When automating a chain of things to craft by recursively looking for the ingredients you need, you end up with twice the copper wire you would need and 10 times the concret.
And that is the reason i considered this an issue.

I am going to commit a version where it is optional.
