### ISSUE TITLE
Don't add signals for recipes that won't work

### ISSUE THREAD

**Issue by jcranmer** [theRustyKnife/CraftingCombinator#5]
If you try to use this mod with Angel's, you get a lot of useless recipes for things like the fluid splitters or converters. Since these aren't exposed to the user ever, there's no point in setting them.

The way I patched this locally was to disable all hidden recipes from getting virtual signals. A cleaner way that matches the idea of what will really happen would be to eliminate all recipes that are only usable in furnaces--you can't set them as a recipe any way, so there's no point to them.

(Or you could iterate only over those recipe categories that are enabled in assemblers, come to think of it).

**Comment by theRustyKnife** [comment]
I believe this should be fixed by [Nexela's code](https://github.com/theRustyKnife/CraftingCombinator/pull/4).
I think I'll keep the normal furnace virtual recipes for getting their ingredients tho. The recipes have their own tab in the next version (thanks to Nexela again) so it should not be as much of an issue anymore.

I will probably publish a new version even though I planned to add more things before doing so, hopefully everything is in somewhat working order right now.

Cheers TRK

**Comment by theRustyKnife** [comment]
Ok, I just published a new version with the fixes, you can go test it out. Be sure to make a backup of your save before updating tho.

**Comment by Nexela** [comment]
If the fluid recipes are not hidden then fluid splitter recipes may still show up, as I believe one of angel's mods can actually enable some of these recipes.  As for the furnace only recipes, there is no point in removing these as other mods can add these recipes to custom assembling machines.

If you don't want them to show up edit data-final-fixes.lua and find
```lua
local ignore_name_list = {
    -- "angels%-fluid%-splitter-",
    -- "converter%-angels%-",
    "compress%-",
    "uncompress%-",
}
```
And uncomment (remove the --) from the convertor/splitter recipes
