### ISSUE TITLE
Mod Website is 404

### ISSUE THREAD

**Issue by CodingBenny** [theRustyKnife/CraftingCombinator#52]
The homepage link in info.json https://mods.factorio.com/mods/crafting_combinator is redirecting to https://mods.factorio.com/user/crafting_combinator and that does not exist.
In the mods explorer inside factorio the mod portal page is listed anyway.
Maybe link github as homepage?

**Comment by theRustyKnife** [comment]
I completely forgot about this... I just removed the homepage link altogether since I want the mod portal to be the main place for the mod. There are links to all the other places there if need be.

I don't want to make a new version just for this tho, so it'll have to wait until there's more to change.
