### ISSUE TITLE
Crafting combinator in wrong section in deconstruction planner

### ISSUE THREAD

**Issue by CodingBenny** [theRustyKnife/CraftingCombinator#54]
When selecting filters for the deconstruction planner the crafting combinator is not showing up where it should be in the logistics tab: 
![grafik](https://user-images.githubusercontent.com/51423815/61182699-43a7e700-a637-11e9-80b6-4b24177ac994.png)

Instead the module chest is showing up in the unsorted tab:
![grafik](https://user-images.githubusercontent.com/51423815/61182681-0c393a80-a637-11e9-9960-d48a77539d15.png)

**Comment by theRustyKnife** [comment]
Hmm, I guess the module chest should be disguised as the combinator itself then? It wouldn't be an issue, except when you open the chest it would say "Crafting combinator" instead of "Crafting combinator module chest" and the details in the tooltip would still be wrong. I think I can live with that tho.
